### PR TITLE
Feature fix registry clean edge case

### LINKED ISSUE #7: Handle Registry Clean Edge Case
It is possible to get in a state where no manifests are eligible for deletion - which makes it impossible to hit the target utilization of the disk. In this case the proxy should print a warning and allow the registry to return to full operation until the next maintenance window. Currently it will keep trying indefinitely resulting in a 503 for push operations

### PR DESCRIPTION
**Pull request by boxboatmatt**
This PR fixes #7 and updates dependencies

Setting an impossibly low target usage to reproduce with a registry yields something like:
```
time="2023-01-04T18:13:00Z" level=debug msg="registry using 983724032 bytes"
time="2023-01-04T18:13:00Z" level=debug msg="registry target 10485760 bytes"
time="2023-01-04T18:13:00Z" level=info msg="total tags: 20"
time="2023-01-04T18:13:00Z" level=info msg="iteration 0: removing 2 tags"
...
time="2023-01-04T18:13:02Z" level=debug msg="registry using 534601728 bytes"
time="2023-01-04T18:13:02Z" level=debug msg="registry target 10485760 bytes"
time="2023-01-04T18:13:02Z" level=info msg="total tags: 1"
time="2023-01-04T18:13:02Z" level=info msg="iteration 16: removing 1 tags"
...
time="2023-01-04T18:13:02Z" level=debug msg="registry using 489865216 bytes"
time="2023-01-04T18:13:02Z" level=debug msg="registry target 10485760 bytes"
time="2023-01-04T18:13:02Z" level=warning msg="unable to reach regisry target 10485760 bytes  - exiting cleanup with 489865216 bytes"
```

This should prevent the edge case where the clean settings and target usage cannot get below the target threshold either because of large images lurking in the registry or because the cache is sharing a disk.

### CODE REVIEW

File: pkg/proxy/proxy.go [hunk 1]
```diff
@@ -150,11 +151,14 @@ func (proxy *Proxy) cleanup(ctx context.Context) {
...
-	for proxy.removeTags() {
+	remove, _ := proxy.shouldRemoveTags()
+	iteration := 0
+
+	for remove {
 		lruImages := proxy.Cache.GetLruList()
 		common.Log.Infof("total tags: %d", len(lruImages))
-		removalTags := int(float64(len(lruImages)) * proxy.CleanSettings.CleanTagsPercentage)
-		common.Log.Infof("Removing %d tags", removalTags)
+		removalTags := int(math.Max(math.Round(float64(len(lruImages))*proxy.CleanSettings.CleanTagsPercentage), math.Min(float64(iteration), 1)))
```
Comment (jordanjennings) [inline pkg/proxy/proxy.go:160]: minor suggestion - break this into two clearly named variables because the line is really hard to read with the additions, something like:

```
thing1 := math.Round(float64(len(lruImages)) * proxy.CleanSettings.CleanTagsPercentage)
thing2 := math.Min(float64(iteration), 1)
removalTags := int(math.Max(thing1, thing2))
```
but actual meaningful names :D

**Review by jordanjennings — APPROVED** [review]
LGTM - with one minor suggestion
